import React, { useMemo } from 'react';
import {
  BarChart, Bar, LineChart, Line, ComposedChart, Cell,
  XAxis, YAxis, CartesianGrid, Tooltip, Legend, ResponsiveContainer,
  ScatterChart, Scatter, ZAxis,
} from 'recharts';
import { useFilters } from '../App.jsx';
import {
  getData, aggregateByCountry, aggregateByPeriod,
  getChannelBreakdown, getTimeSeriesData, COUNTRIES,
} from '../services/dataService.js';
import KPICard from '../components/KPICard.jsx';
import { fmt } from '../utils/formatters.js';

const CC  = Object.fromEntries(COUNTRIES.map(c => [c.code, c.color]));
const TICK = { fontSize: 11, fill: '#64748b' };
const CHAN_COLORS = ['#3b82f6','#10b981','#f59e0b','#ef4444','#8b5cf6'];

export default function CampaignPerformance() {
  const { filters, selectedCountries } = useFilters();

  const data     = useMemo(() => getData(filters), [filters]);
  const byCtry   = useMemo(() => aggregateByCountry(data), [data]);
  const byMo     = useMemo(() => aggregateByPeriod(data), [data]);
  const channels = useMemo(() => getChannelBreakdown(data), [data]);
  const roiSeries = useMemo(() => getTimeSeriesData(data, 'campaignROI', selectedCountries), [data]);

  const totals = useMemo(() => data.reduce((a, r) => ({
    budget:    a.budget    + r.campaignBudget,
    campaigns: a.campaigns + r.campaignsRun,
    leads:     a.leads     + r.leads,
    newPremium:a.newPremium+ r.newPremium,
  }), { budget: 0, campaigns: 0, leads: 0, newPremium: 0 }), [data]);

  const avgROI    = totals.budget ? Math.round((totals.newPremium / totals.budget) * 10) / 10 : 0;
  const cpLead    = totals.leads  ? Math.round(totals.budget / totals.leads) : 0;

  const ctryROI = byCtry.map(c => ({
    name: COUNTRIES.find(x => x.code === c.country)?.flag + ' ' + c.countryName,
    code: c.country,
    ROI: c.campaignROI,
  }));

  const ctryBudget = byCtry.map(c => ({
    name: COUNTRIES.find(x => x.code === c.country)?.flag + ' ' + c.countryName,
    code: c.country,
    Budget: Math.round(c.campaignBudget / 1000),
    Campaigns: c.campaigns,
  }));

  const budgetTrend = byMo.map(r => ({
    ...r, label: `${r.monthName}'${String(r.year).slice(2)}`,
    cpl: r.leads ? Math.round(r.campaignBudget / r.leads) : 0,
  }));

  return (
    <>
      <div className="kpi-grid">
        <KPICard label="Campaigns Run"      value={fmt.number(totals.campaigns)}     sub="Total campaigns"          accent="#3b82f6" />
        <KPICard label="Total Budget"       value={fmt.currency(totals.budget)}       sub="USD spent"                accent="#ef4444" />
        <KPICard label="Avg Campaign ROI"   value={avgROI + 'x'}                      sub="Premium / budget"         accent="#10b981" />
        <KPICard label="Cost Per Lead"      value={fmt.currency(cpLead, false)}        sub="USD per qualified lead"   accent="#f59e0b" />
        <KPICard label="Leads Generated"    value={fmt.number(totals.leads)}           sub="All channels"             accent="#8b5cf6" />
      </div>

      <div className="charts-row charts-2col">
        <div className="chart-card">
          <div className="chart-header">
            <div className="chart-title">Spend by Channel</div>
            <div className="chart-sub">USD thousands</div>
          </div>
          <ResponsiveContainer width="100%" height={240}>
            <BarChart data={channels} layout="vertical">
              <CartesianGrid strokeDasharray="3 3" stroke="#f1f5f9" />
              <XAxis type="number" tick={TICK} tickFormatter={v => '$' + fmt.number(v * 1000)} />
              <YAxis type="category" dataKey="channel" tick={{ fontSize: 11, fill: '#64748b' }} width={115} />
              <Tooltip formatter={v => ['$' + fmt.number(v * 1000), 'Budget']} />
              <Bar dataKey="spend" name="Spend ($K)" radius={[0,4,4,0]}
                   label={{ position: 'right', fontSize: 10, formatter: v => '$' + Math.round(v / 1000) + 'K' }}>
                {channels.map((_, i) => <Cell key={i} fill={CHAN_COLORS[i % 5]} />)}
              </Bar>
            </BarChart>
          </ResponsiveContainer>
        </div>

        <div className="chart-card">
          <div className="chart-header">
            <div className="chart-title">Leads Generated by Channel</div>
          </div>
          <ResponsiveContainer width="100%" height={240}>
            <BarChart data={channels} layout="vertical">
              <CartesianGrid strokeDasharray="3 3" stroke="#f1f5f9" />
              <XAxis type="number" tick={TICK} tickFormatter={fmt.axis.count} />
              <YAxis type="category" dataKey="channel" tick={{ fontSize: 11, fill: '#64748b' }} width={115} />
              <Tooltip formatter={v => [fmt.number(v), 'Leads']} />
              <Bar dataKey="leads" name="Leads" radius={[0,4,4,0]}>
                {channels.map((_, i) => <Cell key={i} fill={CHAN_COLORS[i % 5]} />)}
              </Bar>
            </BarChart>
          </ResponsiveContainer>
        </div>
      </div>

      <div className="charts-row charts-2col">
        <div className="chart-card">
          <div className="chart-header">
            <div className="chart-title">Campaign ROI by Country</div>
            <div className="chart-sub">Premium generated per $1 spent</div>
          </div>
          <ResponsiveContainer width="100%" height={240}>
            <BarChart data={ctryROI}>
              <CartesianGrid strokeDasharray="3 3" stroke="#f1f5f9" />
              <XAxis dataKey="name" tick={{ fontSize: 10, fill: '#64748b' }} />
              <YAxis tick={TICK} tickFormatter={v => v + 'x'} domain={[0, 'auto']} />
              <Tooltip formatter={v => [v + 'x', 'ROI']} />
              <Bar dataKey="ROI" radius={[4,4,0,0]}>
                {ctryROI.map((e, i) => <Cell key={i} fill={CC[e.code]} />)}
              </Bar>
            </BarChart>
          </ResponsiveContainer>
        </div>

        <div className="chart-card">
          <div className="chart-header">
            <div className="chart-title">Budget & Campaigns by Country</div>
          </div>
          <ResponsiveContainer width="100%" height={240}>
            <BarChart data={ctryBudget}>
              <CartesianGrid strokeDasharray="3 3" stroke="#f1f5f9" />
              <XAxis dataKey="name" tick={{ fontSize: 10, fill: '#64748b' }} />
              <YAxis yAxisId="l" tick={TICK} tickFormatter={v => '$' + v + 'K'} />
              <YAxis yAxisId="r" orientation="right" tick={TICK} />
              <Tooltip />
              <Legend />
              <Bar yAxisId="l" dataKey="Budget"    name="Budget ($K)" fill="#3b82f6" radius={[4,4,0,0]} />
              <Bar yAxisId="r" dataKey="Campaigns" name="# Campaigns" fill="#f59e0b" radius={[4,4,0,0]} />
            </BarChart>
          </ResponsiveContainer>
        </div>
      </div>

      <div className="charts-row charts-1col">
        <div className="chart-card">
          <div className="chart-header">
            <div className="chart-title">Campaign ROI Trend by Country</div>
            <div className="chart-sub">Premium-to-budget ratio month over month</div>
          </div>
          <ResponsiveContainer width="100%" height={240}>
            <LineChart data={roiSeries.map(r => ({ ...r, label: `${r.monthName}'${String(r.year).slice(2)}` }))}>
              <CartesianGrid strokeDasharray="3 3" stroke="#f1f5f9" />
              <XAxis dataKey="label" tick={TICK} interval={5} />
              <YAxis tick={TICK} tickFormatter={v => v + 'x'} />
              <Tooltip formatter={v => [v + 'x', 'ROI']} />
              <Legend />
              {selectedCountries.map(code => {
                const meta = COUNTRIES.find(c => c.code === code);
                return (
                  <Line
                    key={code} dataKey={code} name={meta?.flag + ' ' + meta?.name}
                    stroke={CC[code]} strokeWidth={2} dot={false}
                  />
                );
              })}
            </LineChart>
          </ResponsiveContainer>
        </div>
      </div>

      <div className="charts-row charts-1col">
        <div className="chart-card">
          <div className="chart-header">
            <div className="chart-title">Monthly Budget vs Cost Per Lead</div>
            <div className="chart-sub">Budget (bars) · Cost per lead (line, USD)</div>
          </div>
          <ResponsiveContainer width="100%" height={220}>
            <ComposedChart data={budgetTrend}>
              <CartesianGrid strokeDasharray="3 3" stroke="#f1f5f9" />
              <XAxis dataKey="label" tick={TICK} interval={5} />
              <YAxis yAxisId="l" tick={TICK} tickFormatter={fmt.axis.currency} />
              <YAxis yAxisId="r" orientation="right" tick={TICK} tickFormatter={v => '$' + v} />
              <Tooltip />
              <Legend />
              <Bar     yAxisId="l" dataKey="campaignBudget" name="Budget ($)" fill="#bfdbfe" radius={[3,3,0,0]} />
              <Line    yAxisId="r" dataKey="cpl" name="Cost/Lead ($)" stroke="#ef4444" strokeWidth={2} dot={false} />
            </ComposedChart>
          </ResponsiveContainer>
        </div>
      </div>
    </>
  );
}
